# Site settings
title: "Fieldwork — We Make Things"
title_appendage: " – Fieldwork"
description: "This is a description."
baseurl: "/fieldwork-v2"
asseturl: "https://4dd31530cac686690479-fe99d1e1a6eca87157ebc4c97a827cc2.ssl.cf2.rackcdn.com/2014"
url: "http://madebyfieldwork.com"
collections:
  work:
    output: true
    permalink: /:collection/:path/
  featured:
    output: false
    permalink: /work/:path/

# Build settings
markdown: kramdown
permalink: pretty
sass: 
  sass_dir: css
  sourcemap: true
