# Site settings
title: "Fieldwork — We Make Things"
title_appendage: " – Fieldwork"
description: "This is a description."
baseurl: "/fieldwork-v2"
url: "http://madebyfieldwork.com"

# Build settings
markdown: kramdown
permalink: pretty
sass: 
  sass_dir: css
  sourcemap: true
