# Site settings
title: "Fieldwork — We Make Things"
title_appendage: " – Fieldwork"
description: "This is a description."
baseurl: "/fieldwork-v2"
url: "http://madebyfieldwork.com"
collections:
  work:
    output: true
    permalink: /:collection/:path/
  featured:
    output: false
    permalink: /work/:path/

# Build settings
markdown: kramdown
permalink: pretty
sass: 
  sass_dir: css
  sourcemap: true
